# Generated by Django 2.2 on 2019-04-21 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_currency', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('base_currency', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('at', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['target_currency', 'base_currency'], name='exchange_rate_currencies'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('target_currency', 'base_currency', 'at'), name='exchange_rate_unique'),
        ),
    ]
